### ISSUE TITLE
Uncaught Error: /opt/apps/io.atom.atom/files/share/atom/resources/app.asar.unpacked/node_modules/...

### ISSUE THREAD

**Issue by CRodrigo210** [atom/.github#37]
@adzanmend commented on [Tue Nov 09 2021](https://github.com/atom/atom/issues/23230)

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: Deepin 20.2.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: /opt/apps/io.atom.atom/files/share/atom/resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node: cannot open shared object file: No such file or directory

```
At ELECTRON_ASAR.js:160

Error: /opt/apps/io.atom.atom/files/share/atom/resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/opt/apps/io.atom.atom/files/share/atom/resources/app/static/<embedded>:1:692866)
    at get_KeyboardLayoutManager (/opt/apps/io.atom.atom/files/share/atom/resources/app/static/<embedded>:14:2786167)
    at get_manager (/opt/apps/io.atom.atom/files/share/atom/resources/app/static/<embedded>:14:2786269)
    at Object.getCurrentKeyboardLayout (/opt/apps/io.atom.atom/files/share/atom/resources/app/static/<embedded>:14:2786395)
    at e.keystrokeForKeyboardEvent (/opt/apps/io.atom.atom/files/share/atom/resources/app/static/<embedded>:14:1083385)
    at KeymapManager.keystrokeForKeyboardEvent (/opt/apps/io.atom.atom/files/share/atom/resources/app/static/<embedded>:11:1250646)
    at KeymapManager.handleKeyboardEvent (/opt/apps/io.atom.atom/files/share/atom/resources/app/static/<embedded>:11:1248631)
    at WindowEventHandler.handleDocumentKeyEvent (/opt/apps/io.atom.atom/files/share/atom/resources/app/static/<embedded>:11:284496)
```

### Commands

```
```

### Non-Core Packages

```
language-vue 0.26.0 
```

**Comment by CRodrigo210** [comment]
😁

**Comment by CRodrigo210** [comment]
[]()
